version: '3'
services:
  main-container:
    image: "ubuntu:bionic"
    restart: on-failure
    volumes:
      - /var/lib/docker/volumes/mysql-db:/var/lib/mysql-db
    environment:
      - MYSQL_DATABASE=db_jdbc_lab
      - MYSQL_ROOT_PASSWORD=root
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=db_jdbc_lab
      - DATABASE_PORT=3306
    build:
      context: .
      dockerfile: "Dockerfile"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    ports:
      - 8080:8080
      - 3306:3306
